### PR TITLE
Create tags for rendering.

### PR DESCRIPTION
**Pull request by SalahAdDin**
Update scripts tags.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
@FlipperPA I don't know how can we hadled multiple code blocks in user theme renderings.

**Comment by SalahAdDin** [comment]
I have other problem with this approach: my field here is a strucblock called body, it have many child blocks, one of them is a code block that have inside a field which type is this `wagtailcodeblock`, for this reason i think this approach isn't generally.

@FlipperPA Maybe you can help me with this :D

**Comment by SalahAdDin** [comment]
With two or more block `prism` doesn't works.
notienedelineado

I'm taking the respective `js` files:
scripts-prims
But it still doesn't works.

The most curious thing is that in `firefox` it works fine:
screenshot-2017-10-25 bueno esto es una prueba de que esta mamada funciona - xprende

**Comment by SalahAdDin** [comment]
@FlipperPA Finally i finished this, the problem was with a wrong script file loading: by default `prismjs` take `xml`, `html`, `svg` and `mathtml` like default `markup` language; when we put some of this the `python` try to load the files for this languages, but they don't exist, it make a error and, as the `html` block are before to the other block, it will have a loading error.

Now it works fine:
htmlfile
todobien

**Comment by SalahAdDin** [comment]
@FlipperPA Thank you very much.

We still have to work in a template tag in frontend, isn't it?

**Comment by FlipperPA** [comment]
@SalahAdDin Check out the new version I published, if you would!

I've solved the problem with the conflicted CSS for tag-based languages. Give it a whirl and see what you think. I ended up doing a pretty major refactor.

**Pull request merged**
