### PR TITLE
Fix for Wagtail>=2.13 

### LINKED ISSUE #28: Admin Clientside Error - Wagtail Release >= 2.13
Clientside error on admin when using wagtailcodeblock "_**Uncaught ReferenceError: Prism is not defined at prism_repaint**_". I believe its due to Wagtail recent releases; the error is shown when using versions >= 2.13. 

When viewing the page live everything works fine, the error is only shown on the Wagtail Admin.

image

### PR DESCRIPTION
**Pull request by cybelew**
Resolves #28

Wagtail 2.13+ changes the way CSS & JS should be added to custom StructBlocks (see https://docs.wagtail.io/en/v2.14.1/advanced_topics/customisation/streamfield_blocks.html#id1).

This update is not backwards compatible with Wagtail < 2.13

### CODE REVIEW

**Comment by FlipperPA** [comment]
Thanks @cybelew! I'm going to give this a test now on a few of my sites, and if it all works, I'll publish. I haven't had the cycles to review this, since I've been swamped with some work projects, so I appreciate the contribution!

**Comment by cybelew** [comment]
@FlipperPA No problem, glad it works!

**Comment by FlipperPA** [comment]
@cybelew I'm working up a really big release for tomorrow that increases performance substantially. One thing I noticed is that the block in the Wagtail editor doesn't update in real-time as you type in the textarea, and the textarea doesn't resize automagically to the code inside. Neither of these is the end of the world...

I've started toying with this to fix the first issue, but figured I'd see if you had any ideas:
https://github.com/FlipperPA/wagtailcodeblock/blob/use-cdn-js/wagtailcodeblock/static/wagtailcodeblock/js/wagtailcodeblock.js#L34

**Comment by FlipperPA** [comment]
@cybelew I got it! We just needed to change the event the `keyup`. All good, I'll release later today at `1.25.0.0`.
 
Thanks again!

**Comment by cybelew** [comment]
Oh great!  Sorry, meant to take a look last night, but didn't get the time >.<  Thank you for the release!

**Pull request merged**
